name: Python application

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 0 * * *'
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: |
        python main.py ${{ secrets.TG_BOT_TOKEN }} ${{ secrets.TG_CHAT_ID }} ${{ secrets.UNSPLASH_KEY }} ${{ secrets.OPENAI_HOST }} ${{ secrets.OPENAI_KEY }}
