name: Python application

on:
  schedule:
    # * 是任何值，/5 是每五分钟的意思
    # 这个 cron job 每五分钟运行一次
    - cron:  '30 3,6,13,15,23 * * *'
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: |
        python your-script.py
