name: Python application

on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set environment variables
        env:
          TG_KEY: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          UNSPLASH_KEY: ${{ secrets.UNSPLASH_KEY }}
          OPEN_AI_HOST: ${{ secrets.OPENAI_HOST }}
          OPEN_AI_KEY: ${{ secrets.OPENAI_KEY }}
          CF_R2_HOST: ${{ secrets.CF_R2_HOST }}
          CF_R2_API_KEY: ${{ secrets.CF_R2_API_KEY }}
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: echo "Environment variables set"
      - name: Run script
        run: python main.py
        env:
          TG_KEY: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          UNSPLASH_KEY: ${{ secrets.UNSPLASH_KEY }}
          OPEN_AI_HOST: ${{ secrets.OPENAI_HOST }}
          OPEN_AI_KEY: ${{ secrets.OPENAI_KEY }}
          CF_R2_HOST: ${{ secrets.CF_R2_HOST }}
          CF_R2_API_KEY: ${{ secrets.CF_R2_API_KEY }}
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
